Implemented simple monitor disabling
HSF/prmon pull request #178
Opened 2020-11-20 11:35 UTC by graeme-a-stewart

Added new switch, --disable/-d that allows
monitors to be disabled. Switch can be given
multiple times to disable several components.

Validity of component name is checked and
walllmon cannot be disabled.

Added a new test to ensure that the switch
fucntions correctly.

README.md and help text updated.

2020-11-20 11:40 UTC, graeme-a-stewart commented
There seems to be an issue with our build actions due to a GH security fix. I'll follow up on that.

2020-11-20 14:01 UTC, graeme-a-stewart commented
I think the codefactor warning can be ignored in this case (it's what we used for ages and injecting a bogus "pstree" into the PATH would just cause prmon to break.

2020-11-20 17:10 UTC, amete requested changes
Thanks a lot @graeme-a-stewart. The new functionality looks good to me. I have just a few minor comments.

2020-11-23 09:58 UTC, amete commented
I resolved the simple conflict through the web interface and the associated `CI` passed (although not posted above due to `clang-format` interfering):

https://github.com/HSF/prmon/actions/runs/378656295

We agree to ignore the `CodeFactor` error for the time being. Therefore, I'm merging this now. Many thanks @graeme-a-stewart.

2020-11-23 09:58 UTC, merged