Added new montored value class
HSF/prmon pull request #196
Opened 2021-08-02 10:17 UTC by graeme-a-stewart

This is a big PR, as it introduces a specific class that handles monitored variables, thus refactoring of all monitors to use this class has been added. Also added are namespace `using` statements that define properly the types used by monitors.

The big advantages of this are:
- The intelligent handling of monitored values becomes part of the class, thus less specific code to catch errors needs to be added in each monitor itself
- Specifically values can be flagged as *monotonic*, which protects them against ever decreasing
- Data members and return types now use properly namespaced definitions

This enabled specific monitor protections for decreased values to be removed from a few monitors (iomon, netmon) as well as adding protection for CPU and walltime monitors.

Note that the class does not yet use loggers, but that this should be added (e.g., as a pointer to the logger instance, with `nullptr` meaning fallback to `std::cerr`).

Closes #185

2021-08-02 14:15 UTC, amete requested changes
Thanks a lot for this PR @graeme-a-stewart. In general it looks good. I have only a few minor comments below.

By the way, locally testing your changes I bumped into a failed unit test:

```
12/14 Test #12: testUnits ........................***Failed    3.82 sec
```

with the output:

```
12/14 Testing: testUnits
12/14 Test: testUnits
Command: "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-centos7-gcc11-dbg/bin/python3" "test_cpu.py" "--units" "--time" "3" "--slack" "0" "--interval" "1" 
Directory: /afs/cern.ch/user/a/amete/workspace/prmon-workspace/build/package/tests
"testUnits" start time: Aug 02 16:06 CEST
Output:
----------------------------------------------------------
Will run for 3s using 1 process(es) and 1 thread(s)
[2021-08-02 16:06:17.109] [prmon] [warning] Wallclock time of monitored process was less than the monitoring interval, so average statistics will be unreliable
F
======================================================================
FAIL: test_run_test_with_params (__main__.setup_configurable_test.<locals>.ConfigurableProcessMonitor)
Actual test runner
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/cern.ch/work/a/amete/prmon-workspace/build/package/tests/test_cpu.py", line 82, in test_run_test_with_params
    self.assertLessEqual(
AssertionError: 4 not less than or equal to 3.0 : Too high value for wall time (expected maximum of 3.0, got 4)

----------------------------------------------------------------------
Ran 1 test in 3.724s

FAILED (failures=1)
<end of output>
Test time =   3.82 sec 
----------------------------------------------------------
Test Failed.
"testUnits" end time: Aug 02 16:06 CEST
"testUnits" time elapsed: 00:00:03
----------------------------------------------------------
```

The test succeeded on the second try so we might need to take a closer look at the tests to make them more robust but that's for another issue/PR.

2021-08-02 16:34 UTC, quantum-shift requested changes
Thank you, @graeme-a-stewart. 
I am curious if there may arise a situation in the future where we have to add a metric to a monitor so that we have both monotonic and non-monotonic stats for the same monitor?

2021-08-02 16:34 UTC, quantum-shift commented on package/src/netmon.cpp
>  }
The return type can be ```prmon::monitored_value_map``` as for other monitors.

2021-08-02 16:34 UTC, quantum-shift commented on package/src/iomon.cpp
> +        double(io_param.second.get_value() * sysconf(_SC_CLK_TCK)) /
We can change double to prmon::avg_value for consistency.

2021-08-02 16:34 UTC, quantum-shift commented on package/src/netmon.cpp
> +        double(value.second.get_value() * sysconf(_SC_CLK_TCK)) /
We can change double to prmon::avg_value for consistency.

2021-08-16 13:11 UTC, graeme-a-stewart commented
Latest changes should address all of the review comments - thank you both for them

Still TODO: 
- Documentation update
- Unit tests

2021-08-16 13:13 UTC, graeme-a-stewart commented on package/src/parameter.h
> +  const parameter param;
I think this is sort of an ATLAS convention (I couldn't find anything in <http://isocpp.github.io/CppCoreGuidelines>), but fine with me.

2021-08-18 08:28 UTC, quantum-shift approved these changes

2021-08-18 22:03 UTC, graeme-a-stewart commented
OK, all PR comments have been addressed and last issues fixed. Unit tests are running correctly for the new classes as well, thanks to the Google Test setup in #197.

Will merge this so that @quantum-shift can work on rebasing #195.

2021-08-18 22:03 UTC, merged